---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role docker
# 

#
# vars are namespace with the module name.
#
docker_role_name: docker
COMMON_HOST_BUILD_TARGET: "{{ docker_role_name }}"

#
# OS packages
#

docker_debian_pkgs: []

docker_redhat_pkgs: []
